### ISSUE TITLE
您好，请问怎么联系您？

### ISSUE THREAD

**Issue by starloving** [yejy53/SG-BEV#2]
我看您在360BEV项目中进行了评论。想问您关于同样数据集的问题。您是否成功测试或训练了360BEV项目？
希望和您进行交流。邮箱：776359509@qq.com

**Comment by yejy53** [comment]
嗯嗯，是的，我就是按照github流程来的，他那个数据集确实当时整的挺麻烦的。你也可以加我的微信y18300084937
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, May 30, 2024 04:26 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[yejy53/SG-BEV] 您好，请问怎么联系您？ (Issue #2)

&nbsp;



 
我看您在360BEV项目中进行了评论。想问您关于同样数据集的问题。您是否成功测试或训练了360BEV项目？
 ***@***.***
